name: task
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: any
  bloc: any
  collection: any
  intl: any
  get_it: ^7.6.4
  flutter_bloc: ^8.1.3
  retrofit: ^4.0.1
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^7.0.8
  build_runner: ^2.4.6


flutter:
  uses-material-design: true
